# ref https://raw.githubusercontent.com/nais/naisd/master/nais_example.yaml
image: docker.adeo.no:5000/fo/veilarbperson
replicas:
  min: 2
  max: 4
  cpuThresholdPercentage: 50
port: 8080
healthcheck:
  liveness:
    path: veilarbperson/internal/isAlive
    initialDelay: 20
  readiness:
    path: veilarbperson/internal/selftest
    initialDelay: 20
prometheus:
  enabled: true
  path: veilarbperson/internal/metrics
fasitResources:
  used:
  - alias: srvveilarbperson
    resourceType: credential
  - alias: securityTokenService
    resourceType: baseUrl
  - alias: openam
    resourceType: openam
  - alias: BehandleOppfolgingV1
    resourceType: webserviceendpoint
  - alias: serviceGateway
    resourceType: webservicegateway
  exposed:
  - alias: veilarbpersonAPI
    resourceType: restservice
    path: /veilarbperson/api