apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: veilarbperson
  namespace: pto
  labels:
    team: pto
spec:
  image: ghcr.io/navikt/veilarbperson/veilarbperson:{{version}}
  port: 8080
  webproxy: true
  ingresses:
    - https://veilarbperson.dev-fss-pub.nais.io
    - https://veilarbperson.dev.intern.nav.no
    - https://veilarbperson-q1.nais.preprod.local
    - https://app-q1.dev.adeo.no/veilarbperson
    - https://app.dev.adeo.no/veilarbperson
    - https://app-q1.adeo.no/veilarbperson
    - https://app.dev.intern.nav.no/veilarbperson
  liveness:
    path: veilarbperson/internal/isAlive
    initialDelay: 30
  readiness:
    path: veilarbperson/internal/isReady
    initialDelay: 30
  prometheus:
    enabled: true
    path: veilarbperson/internal/prometheus
  resources:
    limits:
      cpu: "2"
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 1024Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 75
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/dev/srvveilarbperson
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /serviceuser/data/dev/srvveilarbpersonsbs-sbs
        mountPath: /var/run/secrets/nais.io/service_user_sbs
      - kvPath: /kv/preprod/fss/veilarbperson/q1
        mountPath: /var/run/secrets/nais.io/vault
      - kvPath: /apikey/apigw/dev/eksternapp.difi.idporten.authlevel/veilarbperson_q1
        mountPath: /var/run/secrets/nais.io/authlevel
  azure:
    application:
      enabled: true
      claims:
        extra:
          - "NAVident"
  accessPolicy:
    inbound:
      rules:
        - application: veilarbdialog
          namespace: pto
        - application: veilarbaktivitet
          namespace: pto
        - application: paw-proxy
          namespace: paw
        - application: veilarbpersonflate
          namespace: poao
          cluster: dev-gcp
        - application: veilarbvedtaksstotte
          namespace: pto
        - application: veilarboppgave
          namespace: pto
        - application: mulighetsrommet-api
          namespace: team-mulighetsrommet
          cluster: dev-gcp

  env:
    - name: VIRKSOMHET_PERSON_V3_URL
      value: https://app-q1.adeo.no/tpsws-aura/ws/Person/v3
    - name: VIRKSOMHET_EGENANSATT_V1_URL
      value: https://app-q1.adeo.no/tpsws-aura/ws/EgenAnsatt/v1
  envFrom:
    - configmap: pto-config
    - configmap: loginservice-idporten
