# ref https://raw.githubusercontent.com/nais/naiserator/master/examples/nais-max.yaml
apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: veilarbperson
  namespace: default
  cluster: dev-fss
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/veilarbperson/veilarbperson:{{version}}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  port: 8080
  ingresses:
    - https://veilarbperson.nais.adeo.no
    - https://app.adeo.no/veilarbperson
  webproxy: true
  vault:
    enabled: true
  filesFrom:
    configmap: pto-config
  leaderElection: true
  healthcheck:
    liveness:
      path: veilarbperson/internal/isAlive
      initialDelay: 60
      timeout: 10
    readiness:
      path: veilarbperson/internal/isReady
      initialDelay: 60
      timeout: 10
  prometheus:
    enabled: true
    path: veilarbperson/internal/metrics
  resources:
    limits:
      cpu: 3000m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
