apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: veilarbperson
  namespace: pto
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/veilarbperson/veilarbperson:{{version}}
  port: 8080
  webproxy: true
  ingresses:
    - https://veilarbperson.nais.adeo.no
    - https://app.adeo.no/veilarbperson
  liveness:
    path: veilarbperson/internal/isAlive
    initialDelay: 30
  readiness:
    path: veilarbperson/internal/isReady
    initialDelay: 30
  prometheus:
    enabled: true
    path: veilarbperson/internal/prometheus
  resources:
    limits:
      cpu: "2"
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 1024Mi
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 75
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/prod/srvveilarbperson
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /serviceuser/data/prod/srvveilarbpersonsbs-sbs
        mountPath: /var/run/secrets/nais.io/service_user_sbs
      - kvPath: /kv/prod/fss/veilarbperson/default
        mountPath: /var/run/secrets/nais.io/vault
      - kvPath: /apikey/apigw/prod/eksternapp.difi.idporten.authlevel/veilarbperson
        mountPath: /var/run/secrets/nais.io/authlevel
  env:
    - name: VIRKSOMHET_PERSON_V3_URL
      value: https://app.adeo.no/tpsws-aura/ws/Person/v3
  envFrom:
    - configmap: pto-config
    - configmap: loginservice-idporten
