# ref https://raw.githubusercontent.com/nais/naiserator/master/examples/nais-max.yaml
apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: veilarbperson
  namespace: {{namespace}}
  cluster: dev-fss
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/veilarbperson/veilarbperson:{{version}}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  port: 8080
  ingresses:
    - https://veilarbperson-{{namespace}}.nais.preprod.local
    - https://app-{{namespace}}.adeo.no/veilarbperson
  webproxy: true
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/dev/srvveilarbperson
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /kv/preprod/fss/veilarbperson/{{namespace}}
        mountPath: /var/run/secrets/nais.io/vault
  envFrom:
    - configmap: pto-config
  leaderElection: true
  liveness:
    path: veilarbperson/internal/isAlive
    initialDelay: 60
    timeout: 10
  readiness:
    path: veilarbperson/internal/isReady
    initialDelay: 60
    timeout: 10
  prometheus:
    enabled: true
    path: veilarbperson/internal/metrics
  resources:
    limits:
      cpu: 3000m
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 512Mi
