apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: veilarbperson
  namespace: obo
  labels:
    team: obo
spec:
  image: {{image}}
  port: 8080
  webproxy: true
  ingresses:
    - https://veilarbperson.intern.dev.nav.no
  liveness:
    path: veilarbperson/internal/isAlive
    initialDelay: 30
  readiness:
    path: veilarbperson/internal/isReady
    initialDelay: 30
  prometheus:
    enabled: true
    path: veilarbperson/internal/prometheus
  resources:
    limits:
      cpu: "2"
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 1024Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 75
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
  accessPolicy:
    inbound:
      rules:
        - application: veilarbpersonflate
          namespace: poao
          cluster: dev-gcp
        - application: veilarbvedtaksstotte
          namespace: obo
        - application: veilarboppgave
          namespace: obo
          cluster: dev-gcp
        - application: arbeidssokerregistrering-for-veileder
          namespace: paw
          cluster: dev-gcp
        - application: azure-token-generator
          namespace: aura
          cluster: dev-gcp
    outbound:
      rules:
        - application: kodeverk-api
          namespace: team-rocket
        - application: digdir-krr-proxy
          namespace: team-rocket
        - application: poao-tilgang
          namespace: poao
        - application: paw-arbeidssoekerregisteret-api-oppslag
          namespace: paw
        - application: skjermede-personer-pip
          namespace: nom
        - application: norg2
          namespace: org
        - application: veilarboppfolging
          namespace: poao
        - application: repr-api
          namespace: repr
        - application: inngar
          namespace: dab
      external:
        - host: pdl-api.dev-fss-pub.nais.io
        - host: regoppslag.dev-fss-pub.nais.io
        - host: pam-cv-api-gcp.intern.dev.nav.no
  env:
    - name: KODEVERK_URL
      value: http://kodeverk-api.team-rocket
    - name: KODEVERK_SCOPE
      value: api://dev-gcp.team-rocket.kodeverk-api/.default
    - name: KONTAKT_OG_RESERVASJONSREGISTERET_API_URL
      value: http://digdir-krr-proxy.team-rocket
    - name: KONTAKT_OG_RESERVASJONSREGISTERET_SCOPE
      value: api://dev-gcp.team-rocket.digdir-krr-proxy/.default
    - name: PAM_CV_API_SCOPE
      value: api://dev-gcp.teampam.pam-cv-api-gcp/.default
    - name: PAM_CV_API_URL
      value: https://pam-cv-api-gcp.intern.dev.nav.no/pam-cv-api
    - name: REPR_API_SCOPE
      value: api://dev-gcp.repr.repr-api/.default
    - name: REPR_API_URL
      value: http://repr-api.repr
    - name: PDL_API_SCOPE
      value: api://dev-fss.pdl.pdl-api/.default
    - name: PDL_API_URL
      value: https://pdl-api.dev-fss-pub.nais.io
    - name: POAO_TILGANG_URL
      value: http://poao-tilgang.poao
    - name: POAO_TILGANG_SCOPE
      value: api://dev-gcp.poao.poao-tilgang/.default
    - name: REGOPPSLAG_SCOPE
      value: api://dev-fss.teamdokumenthandtering.regoppslag/.default
    - name: REGOPPSLAG_URL
      value: https://regoppslag.dev-fss-pub.nais.io
    - name: SKJERMEDE_PERSONER_PIP_SCOPE
      value: api://dev-gcp.nom.skjermede-personer-pip/.default
    - name: SKJERMEDE_PERSONER_PIP_URL
      value: http://skjermede-personer-pip.nom
    - name: VEILARBOPPFOLGING_SCOPE
      value: api://dev-gcp.poao.veilarboppfolging/.default
    - name: VEILARBOPPFOLGING_URL
      value: http://veilarboppfolging.poao/veilarboppfolging
    - name: OPPSLAG_ARBEIDSSOEKERREGISTERET_URL
      value: http://paw-arbeidssoekerregisteret-api-oppslag.paw
    - name: OPPSLAG_ARBEIDSSOEKERREGISTERET_SCOPE
      value: api://dev-gcp.paw.paw-arbeidssoekerregisteret-api-oppslag/.default
    - name: NORG2_URL
      value: http://norg2.org/norg2
    - name: NORG2_SCOPE
      value: api://dev-gcp.org.norg2/.default

