apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: veilarbperson
  namespace: pto
  labels:
    team: pto
spec:
  image: {{image}}
  port: 8080
  webproxy: true
  ingresses:
    - https://veilarbperson.dev-fss-pub.nais.io
    - https://veilarbperson.dev.intern.nav.no
    - https://veilarbperson-q1.nais.preprod.local
    - https://app-q1.dev.adeo.no/veilarbperson
    - https://app.dev.adeo.no/veilarbperson
    - https://app-q1.adeo.no/veilarbperson
    - https://app.dev.intern.nav.no/veilarbperson
  liveness:
    path: veilarbperson/internal/isAlive
    initialDelay: 30
  readiness:
    path: veilarbperson/internal/isReady
    initialDelay: 30
  prometheus:
    enabled: true
    path: veilarbperson/internal/prometheus
  resources:
    limits:
      cpu: "2"
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 1024Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 75
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/dev/srvveilarbperson
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /serviceuser/data/dev/srvveilarbpersonsbs-sbs
        mountPath: /var/run/secrets/nais.io/service_user_sbs
      - kvPath: /kv/preprod/fss/veilarbperson/q1
        mountPath: /var/run/secrets/nais.io/vault
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
  accessPolicy:
    inbound:
      rules:
        - application: veilarbdialog
          namespace: pto
        - application: veilarbaktivitet
          namespace: pto
        - application: paw-proxy
          namespace: paw
        - application: veilarbpersonflate
          namespace: poao
          cluster: dev-gcp
        - application: veilarbvedtaksstotte
          namespace: pto
        - application: veilarboppgave
          namespace: pto
        - application: mulighetsrommet-api
          namespace: team-mulighetsrommet
          cluster: dev-gcp
        - application: arbeidssokerregistrering-for-veileder
          namespace: paw
          cluster: dev-gcp
        - application: azure-token-generator
          namespace: aura
          cluster: dev-gcp

  env:
    - name: KODEVERK_URL
      value: https://kodeverk-api.nav.no
    - name: KODEVERK_SCOPE
      value: api://dev-gcp.team-rocket.kodeverk-api/.default
    - name: KONTAKT_OG_RESERVASJONSREGISTERET_API_URL
      value: https://digdir-krr-proxy.intern.dev.nav.no
    - name: KONTAKT_OG_RESERVASJONSREGISTERET_SCOPE
      value: api://dev-gcp.team-rocket.digdir-krr-proxy/.default
    - name: PAM_CV_API_SCOPE
      value: api://dev-gcp.teampam.pam-cv-api-gcp/.default
    - name: PAM_CV_API_URL
      value: https://pam-cv-api-gcp.intern.dev.nav.no/pam-cv-api
    - name: PDL_API_SCOPE
      value: api://dev-fss.pdl.pdl-api/.default
    - name: REPR_API_SCOPE
      value: api://dev-fss.pdl.pdl-web/.default
    - name: REPR_API_URL
      value: https://pdl-fullmakt.dev.intern.nav.no
    - name: PDL_API_URL
      value: http://pdl-api.pdl.svc.nais.local
    - name: POAO_TILGANG_URL
      value: http://poao-tilgang.poao.svc.nais.local
    - name: POAO_TILGANG_SCOPE
      value: api://dev-fss.poao.poao-tilgang/.default
    - name: REGOPPSLAG_SCOPE
      value: api://dev-fss.teamdokumenthandtering.regoppslag/.default
    - name: REGOPPSLAG_URL
      value: https://regoppslag.dev.intern.nav.no
    - name: SKJERMEDE_PERSONER_PIP_SCOPE
      value: api://dev-gcp.nom.skjermede-personer-pip/.default
    - name: SKJERMEDE_PERSONER_PIP_URL
      value: https://skjermede-personer-pip.intern.dev.nav.no
    - name: VEILARBOPPFOLGING_SCOPE
      value: api://dev-fss.pto.veilarboppfolging/.default
    - name: VEILARBOPPFOLGING_URL
      value: https://veilarboppfolging-q1.nais.preprod.local/veilarboppfolging
    - name: VEILARBREGISTRERING_SCOPE
      value: api://dev-gcp.paw.veilarbregistrering/.default
    - name: VEILARBREGISTRERING_URL
      value: https://veilarbregistrering.intern.dev.nav.no
    - name: KONTOREGISTER_PERSON_V1_SCOPE
      value: api://dev-gcp.okonomi.sokos-kontoregister-person/.default
    - name: KONTOREGISTER_PERSON_V1_URL
      value: https://sokos-kontoregister-person.intern.dev.nav.no
    - name: AIA_BACKEND_URL
      value: https://www.intern.dev.nav.no/aia-backend
    - name: AIA_BACKEND_SCOPE
      value: api://dev-gcp.paw.paw-arbeidssoker-besvarelse/.default
    - name: OPPSLAG_ARBEIDSSOEKERREGISTERET_URL
      value: https://oppslag-arbeidssoekerregisteret.intern.dev.nav.no
    - name: OPPSLAG_ARBEIDSSOEKERREGISTERET_SCOPE
      value: api://dev-gcp.paw.paw-arbeidssoekerregisteret-api-oppslag/.default

  envFrom:
    - configmap: pto-config
    - configmap: loginservice-idporten
