apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: veilarbperson
  namespace: {{namespace}}
  cluster: dev-fss
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/veilarbperson/veilarbperson:{{version}}
  port: 8080
  webproxy: true
  ingresses:
    - https://veilarbperson-{{namespace}}.nais.preprod.local
    - https://app-{{namespace}}.adeo.no/veilarbperson
  liveness:
    path: veilarbperson/internal/isAlive
    initialDelay: 30
  readiness:
    path: veilarbperson/internal/isReady
    initialDelay: 30
  prometheus:
    enabled: true
    path: veilarbperson/internal/prometheus
  resources:
    limits:
      cpu: "2"
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 1024Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 75
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/dev/srvveilarbperson
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /kv/preprod/fss/veilarbperson/{{namespace}}
        mountPath: /var/run/secrets/nais.io/vault
      - kvPath: /apikey/apigw/dev/eksternapp.difi.idporten.authlevel/veilarbperson_{{namespace}}
        mountPath: /var/run/secrets/nais.io/authlevel
  envFrom:
    - configmap: pto-config
