query($ident: ID!, $historikk: Boolean!) {
    hentPerson(ident: $ident) {
        navn(historikk: $historikk) {
            fornavn
            mellomnavn
            etternavn
            forkortetNavn
        }
        foedsel {
            foedselsdato
        }
        kjoenn {
            kjoenn
        }
        folkeregisteridentifikator(historikk: $historikk) {
            identifikasjonsnummer
            status
            type
        }
        statsborgerskap(historikk: $historikk) {
            land
        }
        doedsfall {
            doedsdato
        }
        sivilstand(historikk:$historikk) {
            type
            gyldigFraOgMed
            relatertVedSivilstand
        }
        forelderBarnRelasjon {
            minRolleForPerson
            relatertPersonsRolle
            relatertPersonsIdent
        }
        telefonnummer {
            landskode
            nummer
            prioritet
            metadata {
                master
                endringer {
                    type,
                    registrert,
                    registrertAv,
                    systemkilde,
                    kilde
                }
            }
        }
        sikkerhetstiltak {
            tiltakstype
            beskrivelse
            gyldigFraOgMed
            gyldigTilOgMed
        }
        adressebeskyttelse(historikk:$historikk) {
            gradering
        }
        bostedsadresse(historikk:$historikk) {
            gyldigFraOgMed
            gyldigTilOgMed
            coAdressenavn
            vegadresse {
                matrikkelId
                postnummer
                husnummer
                husbokstav
                kommunenummer
                adressenavn
            }
            matrikkeladresse {
                matrikkelId
                bruksenhetsnummer
                tilleggsnavn
                postnummer
                kommunenummer
            }
            utenlandskAdresse {
                adressenavnNummer
                bygningEtasjeLeilighet
                postboksNummerNavn
                postkode
                bySted
                regionDistriktOmraade
                landkode
            }
            ukjentBosted {
                bostedskommune
            }
            metadata {
                master
            }
        }
        oppholdsadresse(historikk:$historikk) {
            gyldigFraOgMed
            gyldigTilOgMed
            coAdressenavn
            oppholdAnnetSted
            vegadresse {
                matrikkelId
                husnummer
                husbokstav
                bruksenhetsnummer
                adressenavn
                kommunenummer
                bydelsnummer
                tilleggsnavn
                postnummer
            }
            matrikkeladresse {
                matrikkelId
                bruksenhetsnummer
                tilleggsnavn
                postnummer
                kommunenummer
            }
            utenlandskAdresse {
                adressenavnNummer
                bygningEtasjeLeilighet
                postboksNummerNavn
                postkode
                bySted
                regionDistriktOmraade
                landkode
            }
            metadata {
                master
            }
        }
        kontaktadresse(historikk:$historikk) {
            type
            gyldigFraOgMed
            gyldigTilOgMed
            coAdressenavn
            vegadresse {
                matrikkelId
                postnummer
                husnummer
                husbokstav
                adressenavn
                kommunenummer
            }
            postboksadresse {
                postbokseier
                postboks
                postnummer
            }
            utenlandskAdresse {
                adressenavnNummer
                bygningEtasjeLeilighet
                postboksNummerNavn
                postkode
                bySted
                regionDistriktOmraade
                landkode
            }
            utenlandskAdresseIFrittFormat {
                adresselinje1
                adresselinje2
                adresselinje3
                postkode
                byEllerStedsnavn
                landkode
            }
            postadresseIFrittFormat {
                adresselinje1
                adresselinje2
                adresselinje3
                postnummer
            }
            metadata {
                master
            }
        }
    }
}

