query($ident: ID!, $historikk: Boolean!) {
    hentPerson(ident: $ident) {
        tilrettelagtKommunikasjon {
            talespraaktolk {
                spraak
            }
            tegnspraaktolk {
                spraak
            }
        }
    }
}
