query($ident: ID!, $historikk: Boolean!) {
    hentPerson(ident: $ident) {
        vergemaalEllerFremtidsfullmakt(historikk:$historikk) {
            type
            embete
            vergeEllerFullmektig {
                navn {
                    fornavn
                    mellomnavn
                    etternavn
                }
                identifiserendeInformasjon {
                    navn {
                        fornavn
                        mellomnavn
                        etternavn
                    }
                }
                motpartsPersonident
                omfang
            }
            folkeregistermetadata {
                ajourholdstidspunkt
                gyldighetstidspunkt
            }
        }
    }
}

