query($identer: [ID!]!, $historikk: Boolean!) {
    hentPersonBolk(identer: $identer) {
        ident,
        person {
            navn(historikk: $historikk) {
                fornavn
                mellomnavn
                etternavn
                forkortetNavn
                metadata {
                    master
                }
            }
            foedsel {
                foedselsdato
            }
            kjoenn {
                kjoenn
            }
            folkeregisteridentifikator(historikk: $historikk) {
                identifikasjonsnummer
                status
                type
            }
            doedsfall {
                doedsdato
            }
            adressebeskyttelse {
                gradering
            }
            bostedsadresse(historikk:$historikk) {
                vegadresse {
                    matrikkelId
                    postnummer
                    husnummer
                    husbokstav
                    kommunenummer
                    adressenavn
                }
                utenlandskAdresse {
                    adressenavnNummer
                    bygningEtasjeLeilighet
                    postboksNummerNavn
                    postkode
                    bySted
                    regionDistriktOmraade
                    landkode
                }
                matrikkeladresse {
                    matrikkelId
                    bruksenhetsnummer
                    tilleggsnavn
                    postnummer
                    kommunenummer
                }
                ukjentBosted {
                    bostedskommune
                }
            }
         },
        code
    }
}
